# Generated by Django 3.0.6 on 2020-05-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='img',
        ),
    ]
